//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorNavigator.MapEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndoorNavigator.MapEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutBoxTitle {
            get {
                return ResourceManager.GetString("AboutBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vicey Wang.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string CursorStatusTemplate {
            get {
                return ResourceManager.GetString("CursorStatusTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EntryNode {
            get {
                object obj = ResourceManager.GetObject("EntryNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GuideNode {
            get {
                object obj = ResourceManager.GetObject("GuideNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPG|*.jpg|PNG|*.png|BMP|*.bmp|All files|*.*.
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string InfoDialogTitle {
            get {
                return ResourceManager.GetString("InfoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument.
        /// </summary>
        internal static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid element.
        /// </summary>
        internal static string InvalidElementError {
            get {
                return ResourceManager.GetString("InvalidElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid map file.
        /// </summary>
        internal static string InvalidMapFileError {
            get {
                return ResourceManager.GetString("InvalidMapFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string InvalidValueError {
            get {
                return ResourceManager.GetString("InvalidValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LinkIcon {
            get {
                object obj = ResourceManager.GetObject("LinkIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map file|*.xml|All files|*.*.
        /// </summary>
        internal static string MapFileFilter {
            get {
                return ResourceManager.GetString("MapFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current floor: {0} Canvas size: {1}.
        /// </summary>
        internal static string MapStatusTemplate {
            get {
                return ResourceManager.GetString("MapStatusTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current map.
        /// </summary>
        internal static string NoCurrentMapError {
            get {
                return ResourceManager.GetString("NoCurrentMapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected floor.
        /// </summary>
        internal static string NoSelectedFloorError {
            get {
                return ResourceManager.GetString("NoSelectedFloorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a floor.
        /// </summary>
        internal static string PleaseSelectFloorAlert {
            get {
                return ResourceManager.GetString("PleaseSelectFloorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset canvas size to mininal map size?.
        /// </summary>
        internal static string ResetCanvasSizeToMinimalNotification {
            get {
                return ResourceManager.GetString("ResetCanvasSizeToMinimalNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save map?.
        /// </summary>
        internal static string SaveMapNotification {
            get {
                return ResourceManager.GetString("SaveMapNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected node type.
        /// </summary>
        internal static string UnexpectedTypeError {
            get {
                return ResourceManager.GetString("UnexpectedTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported version.
        /// </summary>
        internal static string UnsupportedVersionError {
            get {
                return ResourceManager.GetString("UnsupportedVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use background image size for current canvas size?.
        /// </summary>
        internal static string UseBackgroundImageSizeNotification {
            get {
                return ResourceManager.GetString("UseBackgroundImageSizeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionInfoTemplate {
            get {
                return ResourceManager.GetString("VersionInfoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WallNode {
            get {
                object obj = ResourceManager.GetObject("WallNode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
